In [3]:
import numpy as np
import torch

##  choice

pytorchにnumpyのようなchoice（ランダムにtorch.tensorから取得する）は無いので，以下のような代替を利用する必要がある．以下では，10個のサンプルを取得する．

### データの作成 

In [4]:
a = torch.from_numpy(np.arange(10000, 10100))
a

tensor([10000, 10001, 10002, 10003, 10004, 10005, 10006, 10007, 10008, 10009,
        10010, 10011, 10012, 10013, 10014, 10015, 10016, 10017, 10018, 10019,
        10020, 10021, 10022, 10023, 10024, 10025, 10026, 10027, 10028, 10029,
        10030, 10031, 10032, 10033, 10034, 10035, 10036, 10037, 10038, 10039,
        10040, 10041, 10042, 10043, 10044, 10045, 10046, 10047, 10048, 10049,
        10050, 10051, 10052, 10053, 10054, 10055, 10056, 10057, 10058, 10059,
        10060, 10061, 10062, 10063, 10064, 10065, 10066, 10067, 10068, 10069,
        10070, 10071, 10072, 10073, 10074, 10075, 10076, 10077, 10078, 10079,
        10080, 10081, 10082, 10083, 10084, 10085, 10086, 10087, 10088, 10089,
        10090, 10091, 10092, 10093, 10094, 10095, 10096, 10097, 10098, 10099],
       dtype=torch.int32)

### randintを用いる場合

In [7]:
random_index = torch.randint(0,100,size=(10,))
print(random_index)
samples = a[random_index]
print(samples)

tensor([87, 81,  7, 45, 38, 96, 36, 50, 30, 51])
tensor([10087, 10081, 10007, 10045, 10038, 10096, 10036, 10050, 10030, 10051],
       dtype=torch.int32)


もちろんインデックスはndarrayでもよい

In [8]:
random_index = np.random.randint(0,100,size=(10,))
print(random_index)
samples = a[random_index]
print(samples)

[ 8 13  4 84 83 53 27  0 48 87]
tensor([10008, 10013, 10004, 10084, 10083, 10053, 10027, 10000, 10048, 10087],
       dtype=torch.int32)


### randomに並び替えられたインデックスを取得し，そこから欲しい個数分取得する 

In [10]:
random_index_all = torch.randperm(len(a))
random_index = random_index_all[:10]
print(random_index)
samples = a[random_index]
print(samples)

tensor([ 8, 19, 54, 96, 57, 17, 83, 79, 14, 64])
tensor([10008, 10019, 10054, 10096, 10057, 10017, 10083, 10079, 10014, 10064],
       dtype=torch.int32)
